// Combine the GeoJSON map data and farmer profiles into one JavaScript file so the dashboard can load them directly without using fetch()
const fs = require("node:fs");
const path = require("node:path");
const read = (name) =>
  JSON.parse(fs.readFileSync(path.join(__dirname, name), "utf8"));
const data = {
  geojson: read("mdb_geo_json.json"),
  farmers: read("farmers.json"),
};
fs.writeFileSync(
  path.join(__dirname, "dashboard-data.js"),
  "// Generated by Map/build-data.cjs; edit the source JSON files.\n" +
    "window.basinData = " + JSON.stringify(data) + ";\n",
);
console.log("Bundled " + data.geojson.features.length + " regions and " + data.farmers.length + " profiles.");
